# hub
export HUB_CONFIG=$HOME/.config/hub/config

export SCRAPBOOK_DIR="$HOME/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents/scrapbook"

export BOOKMARKS_DIR="$SCRAPBOOK_DIR/pages/bookmarks"

if (( $+commands[ghq] )); then
  export DOTFILE=$(ghq root)/github.com/masa0x80/dotfiles
  export DOTFILE_LOCAL=$(ghq root)/github.com/masa0x80/dotfiles.local
fi
